name: Pull Request Tester
on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'test'

